### ISSUE TITLE
Suggestions: add custom color change points

### ISSUE THREAD

**Issue by Keridos** [Tfarcenim/OverloadedArmorBar#17]
Currently when playing with mods that add a lot of armor, the color is always the last one. Could you consider adding in custom limits in the form below?
`"coloring values=["20,100,250,500,1000,2500"]`

**Comment by Tfarcenim** [comment]
No, 20 point per layer will always be used for consistency with vanilla.

FYI armor values above 30 will do very little even if attributefix is used because of how damage is calculated (30 points is the same protection as 3000 with respect to 99.9999% of damage sources in vanilla and mods).

If you're running out of layers because a mod adds pointlessly large armor values, then copy and paste the layers.
